variable "project_id" {}
variable "project_region" {}
variable "database_type" {}
variable "database_instance_name" {}
variable "machine_type" {}
variable "availability_type" {}
variable "edition" {}
variable "environment" {}
variable "USER_NAME" {}
variable "PASSWORD" {}
variable "database_name" {}
variable "GOOGLE_APPLICATION_CREDENTIALS" {}
variable "vpc_name" {}
variable "route_mode" {}
variable "subnet_name" {}
variable "ip_address_range" {}
variable "stack_type" {}
variable "aggregate_interval" {}
variable "include_all_metadata" {}
variable "allow_traffic_to_cloud_sql" {}
variable "protocol" {}
variable "cloud_sql_port" {}
variable "http_port" {}
variable "https_port" {}
variable "allow_traffic_to_gke" {}
variable "cloud_sql_private_ip" {}
variable "private_ip_type" {}
variable "private_ip_purpose" {}
variable "service_type" {}
variable "kubernetes_cluster" {}
variable "kubernetes_node_pool" {}