name: GCP-CD/CD
on:
  push:
    branches: ["main", "golden", "develop"]
  pull_request:
    types: [opened]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: microservice_artifact-registry
  REGION: asia-south1
  REPOSITORY: asia-south1-docker.pkg.dev/capable-mind-428017-c2/microservice-artifact-registry/user-microservice

jobs:
  deploy_to_artifact_registry:
    runs-on: ubuntu-latest
    steps:
      # Github Code Checkout Action
      - name: Git Checkout
        uses: actions/checkout@v4

      # Install Dependencies for the application
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Install Dependencies
        run: './gradlew build --no-daemon'

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          service_account: "dummy-524@capable-mind-428017-c2.iam.gserviceaccount.com"
          workload_identity_provider: 'projects/929430503076/locations/global/workloadIdentityPools/github-infrastructure-action/providers/github'

      # Setup GCloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Authentication with docker
      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
#
#      - name: Build image
#        run: docker build . --file Dockerfile --tag ${{ env.REPOSITORY }}
#        working-directory: /home/runner/work/Awwwards/Awwwards
#
#
#      - name: Push image
#        run: docker push ${{ env.REPOSITORY }}




