name: INFRASTRUCTURE-PROVISIONING
on:
  push:
    branches: ["main", "golden", "develop"]
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Infrastructure Setup'
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS   }}
