name: INFRASTRUCTURE-PROVISIONING
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Infrastructure Setup'
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          service_account: "dummy-524@capable-mind-428017-c2.iam.gserviceaccount.com"
          workload_identity_provider: 'projects/929430503076/locations/global/workloadIdentityPools/github-action-infrastructure/providers/GitHub'

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan -detailed-exitcode
        env:
          TF_VAR_USER_NAME: ${{ secrets.TF_VAR_USER_NAME }}
          TF_VAR_PASSWORD: ${{ secrets.TF_VAR_PASSWORD }}

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_USER_NAME: ${{ secrets.TF_VAR_USER_NAME }}
          TF_VAR_PASSWORD: ${{ secrets.TF_VAR_PASSWORD }}
